# Generated by Django 2.2.5 on 2019-09-29 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itens',
            name='hasStock',
        ),
    ]
