# Generated by Django 2.2.5 on 2019-09-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0002_remove_itens_hasstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itens',
            name='description',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
